### PR TITLE
Replaces use of deprecated each function to improve PHP7 compatibility

### LINKED ISSUE #13: PHP 7.2 Incompatible
Seeing errors because 

```
ErrorException in ImgixTags.php line 24:
The each() function is deprecated. This message will be suppressed on further calls
```

Looks like it needs to be updated.

### PR DESCRIPTION
**Pull request by philliphartin**
Resolves #13

### CODE REVIEW

**Comment by sg-modlab** [comment]
Would really like to see this be merged in.

File: site/addons/Imgix/ImgixTags.php [hunk 1]
```diff
@@ -21,17 +21,18 @@ protected function categorizedAttributes() {
...
-                $categorized_attrs['imgix_attributes'][$key] = $val;
-            }
-        }
+	    if (is_array($attrs)) {
+		    foreach ($attrs as $key => $val) {
+			    $is_html_attr = in_array($key, self::$html_attributes);
+			    $is_data_attr = strpos($key, 'data-') === 0;
+			    $is_aria_attr = strpos($key, 'aria-') === 0;
+			    if ($is_html_attr || $is_data_attr || $is_aria_attr) {
+				    $categorized_attrs['img_attributes'][$key] = $val;
```
Comment (sherwinski) [inline site/addons/Imgix/ImgixTags.php]: Looks like you've indented all these lines with a combination of tabs and spaces. Can we change it to match the spacing convention in the rest of the file?

**Review by sherwinski — CHANGES_REQUESTED** [review]
Hey @pjhartin thanks for the PR! I'd like to request one small change before we go ahead and merge this. Thanks
